from __future__ import annotations
import textwrap
from .base import ProjectBuilderBase, FileTree

class CommonFilesBuilder(ProjectBuilderBase):
    """Builder for files common to all project types."""

    def build(self, tree: FileTree) -> None:
        tree[".gitignore"] = self._gitignore()
        tree[".python-version"] = self.config.python_version + "\n"
        tree["README.md"] = self._readme()

        if self.config.package_manager == "uv":
            tree["pyproject.toml"] = self._pyproject_toml()
        else:
            tree["requirements.txt"] = self._requirements_txt()

    def _gitignore(self) -> str:
        return textwrap.dedent("""\
            # Python
            __pycache__/
            *.py[cod]
            *$py.class
            *.so
            .Python
            build/
            develop-eggs/
            dist/
            downloads/
            eggs/
            .eggs/
            lib/
            lib64/
            parts/
            sdist/
            var/
            wheels/
            share/python-wheels/
            *.egg-info/
            .installed.cfg
            *.egg
            MANIFEST

            # Virtual environments
            .venv/
            venv/
            ENV/
            env/
            .env

            # Distribution / packaging
            *.whl

            # Unit test / coverage
            htmlcov/
            .tox/
            .nox/
            .coverage
            .coverage.*
            .cache
            nosetests.xml
            coverage.xml
            *.cover
            *.py,cover
            .hypothesis/
            .pytest_cache/
            cover/

            # Jupyter Notebooks
            .ipynb_checkpoints

            # pyenv
            .python-version

            # mypy
            .mypy_cache/
            .dmypy.json
            dmypy.json

            # IDEs
            .idea/
            .vscode/
            *.swp
            *.swo
            *~

            # OS
            .DS_Store
            Thumbs.db
        """)

    def _readme(self) -> str:
        config = self.config
        setup_cmd = {
            "pip": "pip install -r requirements.txt",
            "uv": "uv pip install -r requirements.txt",
            "conda": f"conda env create -f environment.yml && conda activate {config.project_name}",
        }.get(config.package_manager, "pip install -r requirements.txt")

        venv_cmd = {
            "pip": f"python{config.python_version} -m venv .venv && source .venv/bin/activate",
            "uv": f"uv venv --python {config.python_version} .venv && source .venv/bin/activate",
            "conda": f"conda create -n {config.project_name} python={config.python_version} -y && conda activate {config.project_name}",
        }.get(config.package_manager, "python -m venv .venv")

        deps_section = ""
        if config.dependencies:
            deps_list = "\n".join(f"- `{d}`" for d in config.dependencies)
            deps_section = f"\n## Dependencies\n\n{deps_list}\n"

        readme_lines = [
            f"# {config.project_name}",
            "",
            "> Generated by [Python Initializr](https://pystart.io)",
            "",
            f"**Python version:** {config.python_version}",
            f"**Package manager:** {config.package_manager}",
            f"**Project type:** {config.project_type}",
            "",
            "## Getting started",
            "",
            "### 1. Set up your virtual environment",
            "",
            "```bash",
            venv_cmd,
            "```",
            "",
            "### 2. Install dependencies",
            "",
            "```bash",
            setup_cmd,
            "```",
            "",
            "### 3. Run the project",
            "",
            "```bash",
            "python main.py",
            "```",
        ]
        if deps_section:
            readme_lines.append(deps_section)
        readme_lines += ["", "## License", "", "MIT", ""]
        return "\n".join(readme_lines)

    def _requirements_txt(self) -> str:
        config = self.config
        lines = list(config.dependencies)
        if config.project_type == "web-api" and config.framework:
            if config.framework not in [d.lower() for d in lines]:
                lines.insert(0, config.framework)
        return "\n".join(lines) + "\n" if lines else "# Add your dependencies here\n"

    def _pyproject_toml(self) -> str:
        config = self.config
        mn = config.module_name
        deps = list(config.dependencies)
        if config.project_type == "web-api" and config.framework:
            if config.framework not in [d.lower() for d in deps]:
                deps.insert(0, config.framework)

        deps_toml = "\n".join(f'    "{d}",' for d in deps)
        python_requires = f">={config.python_version}"

        build_system = textwrap.dedent("""\
            [build-system]
            requires = ["hatchling"]
            build-backend = "hatchling.build"
        """)

        return textwrap.dedent(f"""\
            [project]
            name = "{config.project_name}"
            version = "0.1.0"
            description = "A Python project generated by Python Initializr"
            readme = "README.md"
            requires-python = "{python_requires}"
            license = {{text = "MIT"}}
            dependencies = [
            {deps_toml}
            ]

            [project.scripts]
            {mn} = "{mn}:main"

            {build_system}
        """)
